import './global.css';

export const metadata = {
  title: 'Welcome to lister',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          nav
          <ul>
            <li>nav item</li>
          </ul>
        </nav>
        <header>header</header>
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
